site_name: Eclipse Scava
docs_dir: docs
site_dir: site

theme:
    name: mkdocs
    highlightjs: true

nav:
    - 'Home' : index.md
    - 'Installation and User Guide' : 'installation-and-user-guide/index.md'
    - 'Contributor Guide' : 'contributors-guide/index.md'
    - 'Developers Guide' : 'developers-guide/index.md'
    - 'Videos and Screencasts' : 'installation-and-user-guide/videos/index.md'
markdown_extensions:
    - toc:
        permalink: ÔÉÅ

plugins:
    - search



